Version 4
SymbolType BLOCK
RECTANGLE Normal -48 -24 64 24
WINDOW 0 8 -24 Bottom 2
WINDOW 3 8 24 Top 2
SYMATTR Prefix X
SYMATTR Value RAD_S_RPM
SYMATTR ModelFile dcmotorMS.lib
PIN -48 0 LEFT 8
PINATTR PinName in
PINATTR SpiceOrder 1
PIN 64 0 RIGHT 8
PINATTR PinName out
PINATTR SpiceOrder 2
